name: Staff Change Request
description: Request to add or remove a staff member
title: "[Staff]: "
labels: ["gist-request"]

body:
  - type: dropdown
    id: action
    attributes:
      label: Action
      options:
        - Add
        - Remove
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: Staff name
      description: Exact name as it should appear
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Reason
      description: Optional
